---
- name: capture current userlist in shared list
  set_fact:
    sshb0t_current_allowed_users: "{{ domain.allowed_users }}"

- name: process each github org
  include_tasks: github-org.yml
  loop: "{{ domain.allowed_github_org | default([]) }}"
  loop_control:
    loop_var: github_org_name

- name: process each gitlab group
  include_tasks: gitlab-group.yml
  loop: "{{ domain.allowed_gitlab_groups | default([]) }}"
  loop_control:
    loop_var: gitlab_group_name

# - name: deduplicate users

- name: assert each user keys on server
  include_tasks: user-keys.yml
  loop: "{{ sshb0t_current_allowed_users | default([]) }}"
  loop_control:
    loop_var: username