---
# https://docs.github.com/en/rest/reference/orgs#list-organization-members
- name: retrieve users in github org
  uri:
    url: "https://{{ github_api_url | default('api.github.com') }}/orgs/{{ github_org_name }}/members"
    status_code: 200
    headers:
      Accept: "application/vnd.github.v3+json"
  register: github_response
  connection: local
  delegate_to: localhost

- name: append users
  set_fact:
    sshb0t_current_allowed_users: "{{
      sshb0t_current_allowed_users +
      (github_response.json | community.general.json_query('[*].login') )
      }}"
