---
- name: "retrieve {{ username }}@{{ domain.url }} keys"
  uri:
    url: "https://{{ domain.url | default('github.com') }}/{{ username }}.keys"
    status_code: "200"
    return_content: yes
  register: username_keys
  connection: local
  delegate_to: localhost

- name: "push {{ username }}@{{ domain.url }} keys to server"
  ansible.posix.authorized_key:
    user: root
    comment: "{{ username }}@{{ domain.url }}"
    key_options: "environment=\"SSH_USER={{ username }}\""
    key: "{{ username_keys.content }}"